image: unsat/serval-tools:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - raco pkg install --auto

run-tests:
  script:
    # Add /usr/lib64 for libunicorn
    - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib64"
    - make -C test all