name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        COMMIT: ${{github.sha}}
      run: docker build . --file scripts/Dockerfile --tag "unsat/serval-tools:$COMMIT"
